/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroBanner: typeof import('./components/HeroBanner.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconLucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    IconLucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    IconLucideBell: typeof import('~icons/lucide/bell')['default']
    IconLucideBriefcaseBusiness: typeof import('~icons/lucide/briefcase-business')['default']
    IconLucideBuilding2: typeof import('~icons/lucide/building2')['default']
    IconLucideBusiness: typeof import('~icons/lucide/business')['default']
    IconLucideCalculator: typeof import('~icons/lucide/calculator')['default']
    IconLucideCamera: typeof import('~icons/lucide/camera')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideCheckCircle2: typeof import('~icons/lucide/check-circle2')['default']
    IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideEnvelope: typeof import('~icons/lucide/envelope')['default']
    IconLucideFileCheck2: typeof import('~icons/lucide/file-check2')['default']
    IconLucideFileClock: typeof import('~icons/lucide/file-clock')['default']
    IconLucideFilePlus2: typeof import('~icons/lucide/file-plus2')['default']
    IconLucideFileText: typeof import('~icons/lucide/file-text')['default']
    IconLucideHandshake: typeof import('~icons/lucide/handshake')['default']
    IconLucideHome: typeof import('~icons/lucide/home')['default']
    IconLucideLandmark: typeof import('~icons/lucide/landmark')['default']
    IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard')['default']
    IconLucideListPlus: typeof import('~icons/lucide/list-plus')['default']
    IconLucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    IconLucideLock: typeof import('~icons/lucide/lock')['default']
    IconLucideLogin: typeof import('~icons/lucide/login')['default']
    IconLucideLogIn: typeof import('~icons/lucide/log-in')['default']
    IconLucideLogOut: typeof import('~icons/lucide/log-out')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconLucideMessagesSquare: typeof import('~icons/lucide/messages-square')['default']
    IconLucidePanelLeft: typeof import('~icons/lucide/panel-left')['default']
    IconLucidePaperclip: typeof import('~icons/lucide/paperclip')['default']
    IconLucidePencil: typeof import('~icons/lucide/pencil')['default']
    IconLucidePhone: typeof import('~icons/lucide/phone')['default']
    IconLucidePlus: typeof import('~icons/lucide/plus')['default']
    IconLucideReceiptText: typeof import('~icons/lucide/receipt-text')['default']
    IconLucideSave: typeof import('~icons/lucide/save')['default']
    IconLucideShieldCheck: typeof import('~icons/lucide/shield-check')['default']
    IconLucideSparkles: typeof import('~icons/lucide/sparkles')['default']
    IconLucideTrash2: typeof import('~icons/lucide/trash2')['default']
    IconLucideUploadCloud: typeof import('~icons/lucide/upload-cloud')['default']
    IconLucideUser: typeof import('~icons/lucide/user')['default']
    IconLucideUserRound: typeof import('~icons/lucide/user-round')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    NotificationDropdown: typeof import('./components/NotificationDropdown.vue')['default']
    PrimaryBtn: typeof import('./components/PrimaryBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    TextareaField: typeof import('./components/TextareaField.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
